"""Run Codex against a fresh clone and open a draft PR. Lockfile-guarded,
record-before-emit (a crash leaves the signature open => no auto-retry, never a
double PR). All I/O is injected via FixerDeps for testability.
"""
from __future__ import annotations
import fcntl
import logging
import shutil
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Callable
from inbox_watcher.prompt import build_fixer_prompt
from inbox_watcher.gitops import repo_url
from inbox_watcher.ledger import DispatchLedger

log = logging.getLogger("inbox_watcher.fixer")


@dataclass
class FixerDeps:
    clone: Callable
    run_codex: Callable
    has_changes: Callable
    commit_branch_push: Callable
    open_draft_pr: Callable
    ledger: DispatchLedger
    rule_meta: dict[str, dict[str, Any]]
    workdir: Path
    lock_path: Path
    owner: str
    base: str
    labels: list[str]
    token: str
    codex_bin: str
    timeout_sec: int


def run_fixer(payload: dict[str, Any], *, deps: FixerDeps, now: str) -> str:
    deps.lock_path.parent.mkdir(parents=True, exist_ok=True)
    lock_fh = open(deps.lock_path, "w")
    try:
        try:
            fcntl.flock(lock_fh, fcntl.LOCK_EX | fcntl.LOCK_NB)
        except BlockingIOError:
            log.info("fixer lock held; skipping %s", payload.get("error_signature"))
            return "skipped_locked"
        return _run_locked(payload, deps=deps, now=now)
    finally:
        try:
            fcntl.flock(lock_fh, fcntl.LOCK_UN)
        finally:
            lock_fh.close()


def _run_locked(payload: dict[str, Any], *, deps: FixerDeps, now: str) -> str:
    sig = payload["error_signature"]
    repo = payload["repo"]
    rule_id = payload["rule_id"]
    priority = payload["priority"]
    meta = deps.rule_meta.get(rule_id, {})

    def _record(status: str, pr_url: str | None = None) -> None:
        deps.ledger.record(error_signature=sig, repo=repo, rule_id=rule_id,
                           priority=priority, mode="live", now=now,
                           status=status, pr_url=pr_url)

    # record-before-emit: mark open BEFORE any irreversible action
    _record("in_progress")

    clone_dir = deps.workdir / sig[:12]
    if clone_dir.exists():
        shutil.rmtree(clone_dir, ignore_errors=True)
    deps.workdir.mkdir(parents=True, exist_ok=True)
    try:
        deps.clone(repo_url(deps.owner, repo), clone_dir)
        prompt = build_fixer_prompt(repo=repo, rule_description=meta.get("description", rule_id),
                                    fix_hint=meta.get("fix_hint"))
        result = deps.run_codex(clone_dir=clone_dir, prompt=prompt,
                                timeout_sec=deps.timeout_sec, codex_bin=deps.codex_bin)
        if not deps.has_changes(clone_dir):
            _record("no_fix")
            return "no_fix"
        branch = f"hermes-fixer/{sig[:12]}"
        deps.commit_branch_push(clone_dir, branch=branch,
                                message=f"hermes-fixer: {meta.get('description', rule_id)}")
        title = f"hermes-fixer: {meta.get('description', rule_id)} ({repo})"
        body = (f"Automated draft fix for `{rule_id}` on `{repo}`.\n\n"
                f"Signature `{sig[:12]}`. Generated by hermes-fixer; **review before merge**.\n\n"
                f"Codex notes:\n\n{(result.stdout or '').strip()[:4000]}")
        url = deps.open_draft_pr(owner=deps.owner, repo=repo, head=branch, base=deps.base,
                                 title=title, body=body, labels=[*deps.labels, priority],
                                 token=deps.token)
        _record("opened", pr_url=url)
        return "opened"
    except Exception as exc:                       # leave it open (no auto-retry, no double-PR)
        log.warning("fixer failed for %s/%s: %s", repo, sig[:12], exc)
        return "error"
    finally:
        shutil.rmtree(clone_dir, ignore_errors=True)
